name: b2t
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip=24.2.0
  - pytorch-cuda=11.8
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0 
  - pip:
    - matplotlib>=3.9.2
    - numpy
    - ftfy
    - regex
    - tqdm
    - pandas
    - scikit-learn
    - transformers
    - scikit-image
    - yake
    - tensorboard
    - git+https://github.com/openai/CLIP
