name: b2t
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip:
    - torch==1.12.1
    - torchvision==0.13.1
    - torchaudio==0.12.1
    - numpy
    - ftfy
    - regex
    - tqdm
    - pandas
    - scikit-learn
    - transformers
    - scikit-image
    - yake