name: b2t
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pytorch-cuda=11.8
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - pip:
    - numpy
    - ftfy
    - regex
    - tqdm
    - pandas
    - scikit-learn
    - transformers
    - scikit-image
    - yake
    - git+https://github.com/openai/CLIP
