#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output_%A.out

#SBATCH --ear=on
#SBATCH --ear-policy=monitoring
#SBATCH --ear-verbose=1

module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/repo/
conda env remove -n b2t
conda env create -f b2t_environment.yaml --debug

source activate b2t
