#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

cd $HOME/FACT25/
conda env create -f b2t_environment.yaml

# Activate your environment
source activate b2t

srun pip install pipenv
srun pipenv --python 3.8
srun pipenv install