#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=PLOT3
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:02:00
#SBATCH --output=slurm_plotting/fig3_imagenet_slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Your job starts in the directory where you call sbatch
cd $HOME/repo/
# Activate your environment
source activate b2t

srun python plotting_fig3.py --dataset imagenet --class_label 'ant, emmet, pismire'
